=== ZlatyChlapec/pb138-projekt-xml-textovky/trunk/textGameXmlSchema.xsd
<?xml version="1.0" encoding="utf-8"?>

<xsd:schema version="1.0"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            elementFormDefault="qualified">

    <xsd:element name="game" type="gameType">
        <xsd:unique name="sceneUnique">
            <xsd:selector xpath="./scene"/>
            <xsd:field xpath="./@id"/>
        </xsd:unique>
    </xsd:element>

    <xsd:complexType name="gameType">
        <xsd:sequence>
            <xsd:element name="scene" type="sceneType" minOccurs="2" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="nonEmptyString" use="required"/>
        <xsd:attribute name="startingScene" type="xsd:positiveInteger" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="sceneType">
        <xsd:sequence>
            <xsd:element name="name" type="nonEmptyString" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="description" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="choices" type="choicesType" minOccurs="1" maxOccurs="1"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:positiveInteger" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="choicesType">
        <xsd:sequence>
            <xsd:element name="choice" type="choiceType" minOccurs="0" maxOccurs="4"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="choiceType">
        <xsd:sequence>
            <xsd:element name="text" type="nonEmptyString" minOccurs="1" maxOccurs="1"/>
        </xsd:sequence>
        <xsd:attribute name="goTo" type="xsd:positiveInteger" use="required"/>
        <xsd:attribute name="points" type="xsd:integer" use="required"/>
    </xsd:complexType>

    <xsd:simpleType name="nonEmptyString">
        <xsd:restriction base="xsd:string">
            <xsd:minLength value="1"/>
        </xsd:restriction>
    </xsd:simpleType>

</xsd:schema>

=== ZlatyChlapec/pb138-projekt-xml-textovky/trunk/src/test/resources/oneScene.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->


<game name="test" startingScene="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="textGameXmlSchema.xsd">
    <scene id="1">
        <name>First scene</name>
        <description>
            This is first scene of the testing XML game.
        </description>
        <choices>
            <choice goTo="1" points="1">
                <text>First choice.</text>
            </choice>
            <choice goTo="1" points="1">
                <text>Second choice.</text>
            </choice>
            <choice goTo="1" points="1">
                <text>Third choice.</text>
            </choice>
        </choices>
    </scene>
</game>

=== ZlatyChlapec/pb138-projekt-xml-textovky/trunk/src/test/resources/StoryValidatorTestFiles/goToSelf.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->


<game name="test" startingScene="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="textGameXmlSchema.xsd">
    <scene id="1">
        <name>First scene</name>
        <description>
            This is first scene of the testing XML game.
        </description>
        <choices>
            <choice goTo="2">
                <text>First choice.</text>
            </choice>
        </choices>
    </scene>
    <scene id="2">
        <name>Second scene</name>
        <description>
            This is second scene of the testing XML game.
        </description>
        <choices>
            <choice goTo="3">
                <text>First choice.</text>
            </choice>
        </choices>
    </scene>
    <scene id="3">
        <name>Third scene</name>
        <description>
            This is third scene of the testing XML game.
        </description>
        <choices>
            <choice goTo="3">
                <text>First choice.</text>
            </choice>
            <choice goTo="5">
                <text>Second choice.</text>
            </choice>
        </choices>
    </scene>
    <scene id="4">
        <name>Fourth scene</name>
        <description>
            Final scene.
        </description>
        <choices/>
    </scene>
    <scene id="5">
        <name>Fifth scene</name>
        <description>
            Final scene.
        </description>
        <choices/>
    </scene>
</game>

=== ZlatyChlapec/pb138-projekt-xml-textovky/trunk/testXML.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->


<game name="test" starting_scene="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="textGameXmlSchema.xsd">
    <scene name="first scene" id="1">
        <description>
            This is first scene of the testing XML game.
        </description>
        <choices>
            <choice goTo="2" points="1">
                <text>First choice.</text>
            </choice>
            <choice goTo="3" points="1">
                <text>Second choice.</text>
            </choice>
            <choice goTo="4" points="1">
                <text>Third choice.</text>
            </choice>
        </choices>
    </scene>
    <scene name="second scene" id="2">
        <description>
            This is second scene of the testing XML game.
        </description>
        <choices>
            <choice goTo="1" points="1">
                <text>First choice.</text>
            </choice>
            <choice goTo="3" points="1">
                <text>Second choice.</text>
            </choice>
            <choice goTo="4" points="1">
                <text>Third choice.</text>
            </choice>
        </choices>
    </scene>
    <scene name="third scene" id="3">
        <description>
            This is third scene of the testing XML game.
        </description>
        <choices>
            <choice goTo="1" points="1">
                <text>First choice.</text>
            </choice>
            <choice goTo="2" points="1">
                <text>Second choice.</text>
            </choice>
            <choice goTo="4" points="1">
                <text>Third choice.</text>
            </choice>
        </choices>
    </scene>
    <scene name="fourth scene" id="4">
        <description>
            This is fourth scene of the testing XML game.
        </description>
        <choices>
            <choice goTo="1" points="1">
                <text>First choice.</text>
            </choice>
            <choice goTo="2" points="1">
                <text>Second choice.</text>
            </choice>
            <choice goTo="3" points="1">
                <text>Third choice.</text>
            </choice>
        </choices>
    </scene>
</game>

=== ZlatyChlapec/pb138-projekt-xml-textovky/trunk/src/test/resources/missingChoiceText.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->


<game name="test" startingScene="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="textGameXmlSchema.xsd">
    <scene id="1">
        <name>First scene</name>
        <description>
            This is first scene of the testing XML game.
        </description>
        <choices>
            <choice goTo="2" points="1"/>
            <choice goTo="3" points="1">
                <text>Second choice.</text>
            </choice>
            <choice goTo="4" points="1">
                <text>Third choice.</text>
            </choice>
        </choices>
    </scene>
    <scene id="2">
        <name>Second scene</name>
        <description>
            This is second scene of the testing XML game.
        </description>
        <choices>
            <choice goTo="1" points="1">
                <text>First choice.</text>
            </choice>
            <choice goTo="3" points="1">
                <text>Second choice.</text>
            </choice>
            <choice goTo="4" points="1">
                <text>Third choice.</text>
            </choice>
        </choices>
    </scene>
    <scene id="3">
        <name>Third scene</name>
        <description>
            This is third scene of the testing XML game.
        </description>
        <choices>
            <choice goTo="1" points="1">
                <text>First choice.</text>
            </choice>
            <choice goTo="2" points="1">
                <text>Second choice.</text>
            </choice>
            <choice goTo="4" points="1">
                <text>Third choice.</text>
            </choice>
        </choices>
    </scene>
    <scene id="4">
        <name>Fourth scene</name>
        <description>
            This is fourth scene of the testing XML game.
        </description>
        <choices>
            <choice goTo="1" points="1">
                <text>First choice.</text>
            </choice>
            <choice goTo="2" points="1">
                <text>Second choice.</text>
            </choice>
            <choice goTo="3" points="1">
                <text>Third choice.</text>
            </choice>
        </choices>
    </scene>
</game>
